#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from benchmarks.common.io_utils import as_text, dump_json, dump_jsonl, load_json, load_jsonl
from benchmarks.common.judge_utils import summarize_judge_rows
from benchmarks.common.openai_client import OpenAICompatibleClient, extract_json_object, extract_message_text, redact_sensitive_config

ACTIVE_DIMENSIONS = [
    "fact_alignment",
    "scholarly_expression",
]


def extract_prediction_from_raw(raw: dict[str, Any]) -> dict[str, Any]:
    response = raw.get("response")
    if not isinstance(response, dict):
        return {}
    content = extract_message_text(response)
    parsed = extract_json_object(content)
    return parsed if isinstance(parsed, dict) else {}


def build_reference_map(reference_run_dir: Path) -> dict[str, dict[str, Any]]:
    reference_map: dict[str, dict[str, Any]] = {}
    rows = load_jsonl(reference_run_dir / "predictions.jsonl")
    for row in rows:
        sample_id = as_text(row.get("sample_id"))
        gt = row.get("ground_truth")
        if not sample_id or not isinstance(gt, dict):
            continue
        reference_map[sample_id] = row
    return reference_map


def render_prompt(
    template: str,
    *,
    task_name: str,
    format_instruction: str,
    ground_truth_full: str,
    ground_truth_evolution: str,
    prediction_evolution: str,
) -> str:
    rendered = template
    rendered = rendered.replace("{{task_name}}", task_name)
    rendered = rendered.replace("{{format_instruction}}", format_instruction)
    # Backward-compatible placeholders.
    rendered = rendered.replace("{{ground_truth}}", ground_truth_full)
    rendered = rendered.replace("{{prediction}}", prediction_evolution)
    # Explicit placeholders.
    rendered = rendered.replace("{{ground_truth_full}}", ground_truth_full)
    rendered = rendered.replace("{{ground_truth_evolution}}", ground_truth_evolution)
    rendered = rendered.replace("{{prediction_evolution}}", prediction_evolution)
    return rendered


DEFAULT_CASE_PAYLOAD_TEMPLATE = """请根据上面的评分规则，对下面这个待评样本进行打分。

[任务名称]
{{task_name}}

[任务格式要求]
{{format_instruction}}

[完整 Ground Truth JSON]
{{ground_truth_full}}

[Ground Truth 的“历代字形演变”]
{{ground_truth_evolution}}

[预测的“历代字形演变”]
{{prediction_evolution}}

只输出 JSON：
{
  "score": 0,
  "reason": ""
}
"""


def clamp_score(value: Any, lo: int = 0, hi: int = 4) -> int:
    try:
        score = float(value)
    except (TypeError, ValueError):
        score = 0.0
    return max(lo, min(hi, int(round(score))))


def parse_single_dimension_score(dimension: str, parsed: dict[str, Any]) -> tuple[float, str]:
    if not isinstance(parsed, dict):
        return 0.0, "parsed output is not a JSON object"

    # Preferred output: {"score": 3, "reason": "..."}
    if "score" in parsed:
        return clamp_score(parsed.get("score")), as_text(parsed.get("reason"))

    # Compatible output: {"<dimension>": {"score": 3, "reason": "..."}}
    dim_data = parsed.get(dimension)
    if isinstance(dim_data, dict):
        return clamp_score(dim_data.get("score")), as_text(dim_data.get("reason"))

    # Fallback: {"<dimension>": 3}
    if dimension in parsed:
        return clamp_score(parsed.get(dimension)), as_text(parsed.get("reason"))

    return 0.0, f"missing score field for {dimension}"


def parse_case_file(path: Path, reference_map: dict[str, dict[str, Any]]) -> dict[str, Any] | None:
    payload = load_json(path)
    sample_id = as_text(payload.get("sample_id")) or path.stem

    # Normalized case generated by prepare_gold_test.py
    if "ground_truth_evolution" in payload and "prediction_evolution" in payload:
        gt_full = payload.get("ground_truth") if isinstance(payload.get("ground_truth"), dict) else {}
        pred_full = payload.get("prediction") if isinstance(payload.get("prediction"), dict) else {}
        gt_evolution = as_text(payload.get("ground_truth_evolution")) or as_text(gt_full.get("历代字形演变"))
        pred_evolution = as_text(payload.get("prediction_evolution")) or as_text(pred_full.get("历代字形演变"))
        return {
            "sample_id": sample_id,
            "task_name": as_text(payload.get("task_name")) or "Ancient Chinese Character Exegesis",
            "format_instruction": as_text(payload.get("format_instruction")),
            "ground_truth_full": gt_full,
            "ground_truth_evolution": gt_evolution,
            "prediction_evolution": pred_evolution,
            "meta": {
                "case_path": str(path.relative_to(REPO_ROOT)),
                "input_type": "normalized_case",
            },
        }

    # raw_responses/*.json
    if "request" in payload and "response" in payload:
        ref = reference_map.get(sample_id)
        if ref is None:
            return None
        gt = ref.get("ground_truth") if isinstance(ref.get("ground_truth"), dict) else {}
        pred_dict = extract_prediction_from_raw(payload)
        return {
            "sample_id": sample_id,
            "task_name": "Ancient Chinese Character Exegesis",
            "format_instruction": "",
            "ground_truth_full": gt,
            "ground_truth_evolution": as_text(gt.get("历代字形演变")),
            "prediction_evolution": as_text(pred_dict.get("历代字形演变")),
            "meta": {
                "case_path": str(path.relative_to(REPO_ROOT)),
                "input_type": "raw_response_json",
            },
        }

    return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Run llm-judge on llm_judge/gold-test with editable prompt template.")
    parser.add_argument("--input-dir", default="llm_judge/gold-test", help="Directory containing *.json test files")
    parser.add_argument("--glob", default="*.json", help="Filename pattern under --input-dir")
    parser.add_argument(
        "--model-config",
        required=True,
        help="Path to judge model config JSON, keys: base_url/model/api_key or api_key_env",
    )
    parser.add_argument(
        "--dimension-prompts-dir",
        default="llm_judge/prompts/dreambenchpp_v1",
        help="Directory containing one prompt template per dimension, file name: <dimension>.txt",
    )
    parser.add_argument(
        "--dimensions",
        default="fact_alignment,scholarly_expression",
        help="Comma-separated dimensions to evaluate; only dimensions with prompt files in --dimension-prompts-dir are allowed",
    )
    parser.add_argument(
        "--output-dir",
        default="llm_judge/results",
        help="Result root dir; script will create timestamped subdir",
    )
    parser.add_argument("--reference-run-dir", default="", help="Required when input files are raw_responses JSON")
    parser.add_argument("--concurrency", type=int, default=8)
    parser.add_argument("--max-tokens", type=int, default=1000)
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--limit", type=int, default=0, help="Optional max cases")
    args = parser.parse_args()

    input_dir = (REPO_ROOT / args.input_dir).resolve()
    if not input_dir.exists():
        raise FileNotFoundError(f"input dir not found: {input_dir}")

    case_paths = sorted(input_dir.glob(args.glob))
    case_paths = [p for p in case_paths if p.is_file() and not p.name.startswith("_")]
    if args.limit > 0:
        case_paths = case_paths[: args.limit]
    if not case_paths:
        raise RuntimeError(f"no files matched {args.glob} in {input_dir}")

    model_config_path = (REPO_ROOT / args.model_config).resolve()
    model_config = load_json(model_config_path)
    client = OpenAICompatibleClient.from_config(model_config)

    dimensions = [item.strip() for item in str(args.dimensions).split(",") if item.strip()]
    if not dimensions:
        raise RuntimeError("no dimensions provided")

    for removed in ("diachronic_consistency", "format_compliance", "diachronic_logic", "key_point_coverage"):
        if removed in dimensions:
            raise RuntimeError(f"{removed} is removed and cannot be used")

    prompts_dir = (REPO_ROOT / args.dimension_prompts_dir).resolve()
    if not prompts_dir.exists():
        raise FileNotFoundError(f"dimension prompts dir not found: {prompts_dir}")

    dimension_templates: dict[str, str] = {}
    dimension_assistant_templates: dict[str, str] = {}
    for dim in dimensions:
        prompt_path = prompts_dir / f"{dim}.txt"
        if not prompt_path.exists():
            raise FileNotFoundError(f"missing prompt template for dimension {dim}: {prompt_path}")
        dimension_templates[dim] = prompt_path.read_text(encoding="utf-8")
        assistant_prompt_path = prompts_dir / f"{dim}.assistant.txt"
        if assistant_prompt_path.exists():
            dimension_assistant_templates[dim] = assistant_prompt_path.read_text(encoding="utf-8")

    case_payload_path = prompts_dir / "case_payload.txt"
    case_payload_template = (
        case_payload_path.read_text(encoding="utf-8") if case_payload_path.exists() else DEFAULT_CASE_PAYLOAD_TEMPLATE
    )

    reference_map: dict[str, dict[str, Any]] = {}
    if args.reference_run_dir:
        reference_run_dir = (REPO_ROOT / args.reference_run_dir).resolve()
        reference_map = build_reference_map(reference_run_dir)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_output_dir = (REPO_ROOT / args.output_dir).resolve() / timestamp
    per_sample_dir = run_output_dir / "per_sample"
    per_sample_dir.mkdir(parents=True, exist_ok=True)

    def run_one(path: Path) -> dict[str, Any]:
        parsed_case = parse_case_file(path, reference_map)
        if parsed_case is None:
            return {
                "sample_id": path.stem,
                "status": "skip",
                "reason": "unsupported_case_format_or_missing_reference",
                "case_path": str(path.relative_to(REPO_ROOT)),
            }

        if not parsed_case["ground_truth_full"]:
            return {
                "sample_id": parsed_case["sample_id"],
                "status": "skip",
                "reason": "ground_truth_full_empty",
                "case_path": parsed_case["meta"]["case_path"],
            }

        scores: dict[str, float] = {}
        reasons: dict[str, str] = {}
        details: dict[str, Any] = {}
        ground_truth_full_text = json.dumps(parsed_case["ground_truth_full"], ensure_ascii=False, indent=2)
        for dim in dimensions:
            template = dimension_templates[dim]
            prompt = render_prompt(
                template,
                task_name=parsed_case["task_name"],
                format_instruction=parsed_case["format_instruction"],
                ground_truth_full=ground_truth_full_text,
                ground_truth_evolution=parsed_case["ground_truth_evolution"],
                prediction_evolution=parsed_case["prediction_evolution"],
            )

            few_shot_messages: list[dict[str, Any]] | None = None
            user_text = prompt
            assistant_prompt = ""
            case_prompt = ""
            if dim in dimension_assistant_templates:
                assistant_prompt = render_prompt(
                    dimension_assistant_templates[dim],
                    task_name=parsed_case["task_name"],
                    format_instruction=parsed_case["format_instruction"],
                    ground_truth_full=ground_truth_full_text,
                    ground_truth_evolution=parsed_case["ground_truth_evolution"],
                    prediction_evolution=parsed_case["prediction_evolution"],
                )
                case_prompt = render_prompt(
                    case_payload_template,
                    task_name=parsed_case["task_name"],
                    format_instruction=parsed_case["format_instruction"],
                    ground_truth_full=ground_truth_full_text,
                    ground_truth_evolution=parsed_case["ground_truth_evolution"],
                    prediction_evolution=parsed_case["prediction_evolution"],
                )
                few_shot_messages = [
                    {"role": "user", "content": prompt},
                    {"role": "assistant", "content": assistant_prompt},
                ]
                user_text = case_prompt

            request, response = client.chat_completion(
                system_prompt="You are a strict grading assistant.",
                user_text=user_text,
                few_shot_messages=few_shot_messages,
                max_tokens=args.max_tokens,
                temperature=float(args.temperature),
                response_format={"type": "json_object"},
            )
            parsed = extract_json_object(extract_message_text(response))
            score, reason = parse_single_dimension_score(dim, parsed)
            scores[dim] = score
            reasons[dim] = reason
            details[dim] = {
                "prompt_template_path": str((prompts_dir / f"{dim}.txt").relative_to(REPO_ROOT)),
                "prompt": prompt,
                "assistant_prompt": assistant_prompt,
                "case_prompt": case_prompt,
                "request": request,
                "response": response,
                "parsed": parsed,
                "score": score,
                "reason": reason,
            }

        scores["overall_score"] = sum(scores[dim] for dim in dimensions) / len(dimensions)

        bundle = {
            "sample_id": parsed_case["sample_id"],
            "case_meta": parsed_case["meta"],
            "inputs": {
                "task_name": parsed_case["task_name"],
                "format_instruction": parsed_case["format_instruction"],
                "ground_truth_full": parsed_case["ground_truth_full"],
                "ground_truth_evolution": parsed_case["ground_truth_evolution"],
                "prediction_evolution": parsed_case["prediction_evolution"],
            },
            "dimensions": dimensions,
            "scores": scores,
            "reasons": reasons,
            "details_by_dimension": details,
        }
        dump_json(per_sample_dir / f"{parsed_case['sample_id']}.json", bundle)

        return {
            "sample_id": parsed_case["sample_id"],
            "status": "ok",
            "case_path": parsed_case["meta"]["case_path"],
            "scores": scores,
        }

    rows: list[dict[str, Any]] = []
    ok = 0
    failed = 0
    skipped = 0

    with ThreadPoolExecutor(max_workers=max(1, int(args.concurrency))) as executor:
        future_map = {executor.submit(run_one, path): path for path in case_paths}
        done = 0
        for future in as_completed(future_map):
            done += 1
            path = future_map[future]
            try:
                row = future.result()
            except Exception as exc:  # noqa: BLE001
                row = {
                    "sample_id": path.stem,
                    "status": "error",
                    "reason": str(exc),
                    "case_path": str(path.relative_to(REPO_ROOT)),
                }

            rows.append(row)
            if row["status"] == "ok":
                ok += 1
            elif row["status"] == "skip":
                skipped += 1
            else:
                failed += 1

            if done % 20 == 0 or done == len(case_paths):
                print(f"[progress] {done}/{len(case_paths)} ok={ok} skip={skipped} error={failed}", flush=True)

    summary_scores = summarize_judge_rows(rows, dimensions)
    summary = {
        "input_dir": str(input_dir.relative_to(REPO_ROOT)),
        "glob": args.glob,
        "dimensions": dimensions,
        "total_cases": len(case_paths),
        "ok_cases": ok,
        "skipped_cases": skipped,
        "error_cases": failed,
        "model_config": redact_sensitive_config(model_config),
        "dimension_prompts_dir": str(prompts_dir.relative_to(REPO_ROOT)),
        "reference_run_dir": args.reference_run_dir,
        **summary_scores,
    }

    dump_json(run_output_dir / "summary.json", summary)
    dump_jsonl(run_output_dir / "results.jsonl", sorted(rows, key=lambda x: x.get("sample_id", "")))

    print(json.dumps(summary, ensure_ascii=False, indent=2), flush=True)
    print(f"[done] results in {run_output_dir}", flush=True)


if __name__ == "__main__":
    main()
